### ISSUE TITLE
Problem with running espressopp.tools.vmd

### ISSUE THREAD

**Issue by NABIAHAMAD** [espressopp/espressopp#181]
Hello,
when i am running espresso++ command
espressopp.tools.vmd.connect(system)
then i got the error which is given below
The new particle position is:
Traceback (most recent call last):
File "espresso.py", line 50, in 
espressopp.tools.vmd.connect(system)
File "/export/apps/espressopp/espressopp-1.9.4.1/espressopp/tools/vmd.py", line 144, in connect
subprocess.Popen([vmd_path, '-e', 'vmd.tcl'])
File "/share/apps/python-2.7/lib/python2.7/subprocess.py", line 390, in init
errread, errwrite)
File "/share/apps/python-2.7/lib/python2.7/subprocess.py", line 1024, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory

Does it need a clean vmd install?
What i have to do, Can anyone please help?
Thanks

**Comment by MrTheodor** [comment]
Do you have vmd installed in your system? Can you run it from the terminal?

**Comment by NABIAHAMAD** [comment]
Hi,
I glad to say you that my Problem with running espressopp.tools.vmd (vmd problems) have solved.
Thank you
