### ISSUE TITLE
MTSAdResS and dump_xtc test fail on Fedora 28

### ISSUE THREAD

**Issue by junghans** [espressopp/espressopp#274]
After #271 everything is fine on Fedora 29, but some test still fail on Fedora 28:
```
      Start 21: MTSAdResS
21/62 Test #21: MTSAdResS ........................***Failed    0.47 sec
/usr/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
..F.
======================================================================
FAIL: test_AT_CG_templates_FAdResS (__main__.TestMTSAdResS)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/espressopp-2.0.1/testsuite/AdResS/MTSAdResS/test_MTSAdResS.py", line 242, in test_AT_CG_templates_FAdResS
    self.assertAlmostEqual(after[0], 9.364194, places=5)
AssertionError: 9.364208038896322 != 9.364194 within 5 places
----------------------------------------------------------------------
Ran 4 tests in 0.079s
FAILED (failures=1)
```
and
```
      Start 28: dump_xtc
28/62 Test #28: dump_xtc .........................***Failed    0.41 sec
/usr/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
F
======================================================================
FAIL: test_simple_xtc (__main__.TestDumpXTC)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/espressopp-2.0.1/testsuite/FileIOTests/dump_xtc/test_dump_xtc.py", line 66, in test_simple_xtc
    self.assertTrue(filecmp.cmp(file_xtc_10atoms, expected_files[1], shallow = False), "!!! Error! Files are not equal!! They should be equal!")
AssertionError: !!! Error! Files are not equal!! They should be equal!
----------------------------------------------------------------------
Ran 1 test in 0.014s
FAILED (failures=1)
```

**Comment by junghans** [comment]
And should mention that is only the case on i386, x86_64 and ppc64le pass.

Details here:
https://copr-be.cloud.fedoraproject.org/results/junghans/espressopp/fedora-28-i386/00866887-espressopp/

So this might be just a roundoff error.

**Comment by jkrajniak** [comment]
Looks like the issue with floating point precision. I would not bother with it, as i386 is quite old arch.

**Comment by junghans** [comment]
I would still like to relax this a bit as the issue is the same on all 32-bit architectures.

**Comment by junghans** [comment]
Let's just exclude these tests for now, Fedora 28 will in end of life in 3 months (May 2019).

**Comment by junghans** [comment]
Workaround in https://github.com/espressopp/fedora-copr/commit/b736e76ba22c910fccbc5acbd3fc87b31e768d5a
