### ISSUE TITLE
Weekly CI fails

### ISSUE THREAD

**Issue by junghans** [espressopp/espressopp#447]
```
======================================================================
ERROR: test_check_dynamic_box (__main__.TestH5MDDynamicBox)
Checks if the change of the box is saved properly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/espressopp/espressopp/testsuite/FileIOTests/h5md/dump_h5md_test.py", line 108, in setUp
    self.dump_h5md = espressopp.io.DumpH5MD(
  File "/__w/espressopp/espressopp/build/espressopp/pmi.py", line 659, in init
    method_self.pmiobject = create(pmiobjectclass, *args, **kwds)
  File "/__w/espressopp/espressopp/build/espressopp/pmi.py", line 315, in create
    obj = __workerCreate(cls, oid, *cargs, **ckwds)
  File "/__w/espressopp/espressopp/build/espressopp/pmi.py", line 334, in __workerCreate
    obj = cls(*args, **kwds)
  File "/__w/espressopp/espressopp/build/espressopp/io/DumpH5MD.py", line 211, in __init__
    self.int_type = np.int32 if is_single_prec else np.int
  File "/usr/lib64/python3.10/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'
```

**Comment by junghans** [comment]
https://github.com/espressopp/espressopp/actions/runs/3931874051

**Comment by junghans** [comment]
@XzzX weekly is broken again....
```
CMake Error at /usr/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES)
Call Stack (most recent call first):
  /usr/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
-- Configuring incomplete, errors occurred!
  /usr/share/cmake-3.28/Modules/FindOpenMP.cmake:580 (find_package_handle_standard_args)
  /usr/share/cmake-3.28/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
  /usr/share/cmake/gromacs_d/gromacs_d-config.cmake:66 (find_dependency)
  CMakeLists.txt:82 (find_package)
```
